### ISSUE TITLE
"Fight Sticks" theme does not allow directional inputs on Fixed Triggers

### ISSUE THREAD

**Issue by FixerFour** [KernelZechs/open-joystick-display#18]
example:
https://i.imgur.com/3vhTdDQ.png

https://i.imgur.com/Ul6FwrG.png

**Comment by KernelZechs** [comment]
I’m currently out I will take a look at this in an hour or two and get back to you. In the meantime can you provide the following:

What version of OJD you are running
What operating system version
What controller or PCB you are using for your fight stick
And a video would be welcomed for debugging purposes.

Thanks

**Comment by FixerFour** [comment]
Windows 10
It's a Hitbox, I'll have to research the PCB.
Just downloaded the app today, should be the latest version.
I can clip a video soon

**Comment by KernelZechs** [comment]
@FixerFour so I was able to replicate the issue. The reason for this is that I added fixed triggers way later and didn't hook it into the fight stick logic. Thankfully this should be fixable. I'll work to get a fix for this as early as tonight, but more than likely tomorrow. Thanks for reporting this!

**Comment by KernelZechs** [comment]
@FixerFour https://www.youtube.com/watch?v=ciDVgfABqec
Here is the fixed code working live. I will release a new version sometime this evening and let you know.

**Comment by KernelZechs** [comment]
@FixerFour 

https://ojdproject.com/downloads/windows/stable/x64/open-joystick-display-2.5.2-x64-windows.zip

Give this a shot and report back to me. Thanks

**Comment by KernelZechs** [comment]
I'm closing out this ticket. If you have any other concerns let me know. Thanks
