### ISSUE TITLE
fight/retro stick 4-position overlays do not recognize Dualshock 4 d-pad

### ISSUE THREAD

**Issue by Tempystral** [KernelZechs/open-joystick-display#20]
In the most recent version of OJD (2.5.2 as of writing), my Dualshock 4 controller is picked up fine and the d-pad is recognized as individual buttons perfectly fine by every overlay, except the 4-position fight stick and retro joysticks. Prior to this release, I was using version 2.0 and that version did respond to my d-pad on those overlays.

I did some digging in the source inspector and found that where I found that `<div ojd-arcade-directional="true">` had property `class="theme-analog"` but its class was not being changed to ``theme-analog-active`` upon receiving input from my d-pad. This behaviour is however present in version 2.0.

I have deleted all the program files as well as the cache in appdata and reinstalled a few times with new configs so I'm not sure if it's the Dualshock 4 or my system, but I think it may be a bug.

**Comment by KernelZechs** [comment]
I can take a look at it and see what I can find. Thanks for helping track this down!

**Comment by KernelZechs** [comment]
@Tempystral I can't replicate this on my side, can you provide a video of your controller and your inputs plus exactly what theme you're using. Also any shots of the inspector would be good to see.

**Comment by KernelZechs** [comment]
I'm closing this ticket until I get further information. Please feel free to post here and I will review it, Thanks.
