### ISSUE TITLE
PowerA Gamecube theme?

### ISSUE THREAD

**Issue by bgiesing** [KernelZechs/open-joystick-display#21]
PowerA sells a GameCube style controller that has all the inputs of the Switch Pro Controller but in a GameCube shell which is supported natively by Steam. Any chance we can get support for that? 

![image](https://user-images.githubusercontent.com/7895463/66294814-7f0d2700-e8af-11e9-9858-2395f960b776.png)

Basically would just be the GameCube theme but add the extra select, screenshot, and home buttons plus L2/R2 and L3/R3

**Comment by KernelZechs** [comment]
I wasn't aware such a controller existed. I suppose I can simply make a clone of the current GC controller and add the extra buttons. My question to you though is, does this belong in the GC section or the Switch section?

**Comment by bgiesing** [comment]
I would put it in the Switch section since it's a controller made for the Switch using Switch input mapping personally.

**Comment by KernelZechs** [comment]
@bgiesing These themes have been added at your request and are available in the latest download (2.6) on the website. Sorry it took so long.
