### ISSUE TITLE
Not really an issue.

### ISSUE THREAD

**Issue by BadFoxDragon** [KernelZechs/open-joystick-display#22]
It works perfectly and I love it. But my viewers can't tell how far I'm pressing the triggers. Is there any way to add this in as a feature? I play a lot of racing games and how far I pull the triggers in really matters.

**Comment by KernelZechs** [comment]
Depends on what controller you have, some have axis support, some don't. Like I know that XBox in Linux has trigger Axis support whereas in Windows it sees the controller with physical buttons (maybe not in game, but as chromium interprets it). 

Either way if you have an axis on your trigger you can build a theme around using the tools mentioned here to show linear movement:

https://ojdproject.com/developer-guide#theme-triggers

If you want to send me a video of the OJD tester and you using your controller I may be able to help and send you a demo theme for you to work around, in the meantime I'm going to close this ticket out.
