### ISSUE TITLE
Bug on Linux Mint 19.3 (Cinnamon)

### ISSUE THREAD

**Issue by Diolinux** [KernelZechs/open-joystick-display#27]
Unlike in GNOME Shell (Tested on Pop!_OS 19.10), double click on Nemo File manager on "open-joystick-display" file, doesn't open the app (executable option properly checked).
Running through terminal "./open-joystick-display" the window of the app open, but nothing appears, the terminal also doesn't show any errors.
![screenshot](https://user-images.githubusercontent.com/13944967/71116848-a176c700-21b3-11ea-8c2a-bfaa4b6fa39f.png)

**Comment by KernelZechs** [comment]
@Diolinux 

For my sanity, can you see if this older version works for you:
https://ojdproject.com/downloads/linux/stable/x64/open-joystick-display-2.5.2-x64-linux.tar.gz

**Comment by Diolinux** [comment]
Hey, thanks for the quick answer. Good news, it works properly with this old version! :)
I was thinking (don't know if it is possible), Linux gamers aren't necessarily really technical people, this way, it will be a good thing if we can open your app without any terminal command or something like that, you may pack this app on a universal format like AppImage, or Flatpak, Snap. This way it can be integrated into the system menu (no matter what distro) and work just like any other regular app.

Thanks and keep doing this great job! :)

**Comment by KernelZechs** [comment]
@Diolinux thanks for getting back to me, with version 3 with the current rewrite I am looking to move to using an AppImage distro as I have simplified distribution of my other projects so that is on my radar.

Also, it is troubling that it doesn't work for you in Mint. I asked you to try the older version because that was the last version I compiled in Mint before migrating to Arch, so I will need to look into that ASAP.

I will post an updated version here once I have an answer, I can only assume ubuntu/mint/debian has some package that is severely out of date that I have compiled against.

**Comment by KernelZechs** [comment]
So upon further investigation it does seem that this application does need to be compiled in debian for it to work correctly, so I will have to setup a few environments for each system. The reason for this is the serialport IO binary used for RetroSpy controller connectivity. Continue using the old version for now but I will have to rethink my deployment process going forward.

Thanks for finding this!

**Comment by Diolinux** [comment]
I'm glad that I could help you in some way. Thanks, I'll keep using the old version, for now, hoping for the future upgrade fix this little bug. I'm sure, an appimage distribution will be great. :)

Thanks again.

**Comment by KernelZechs** [comment]
https://ojdproject.com/downloads/linux/stable/x64/open-joystick-display-2.6-debian-x64-linux.tar.gz
@Diolinux can you try this binary and see if it launches in mint correct? This has been built in a debian environment.

**Comment by Diolinux** [comment]
Hey @KernelZechs, this version is working perfectly. Good Job! :)

**Comment by KernelZechs** [comment]
Awesome, and I've verified that same binary works on various systems including arch, so the website download has been been replaced with that binary. Thanks for bringing this to my attention, I'm going to close this ticket out. Feel free to re-open it if you have any more issues.
