### ISSUE TITLE
Mayflash dreamcast to USB not noticing any inputs in OJD

### ISSUE THREAD

**Issue by zeroviim** [KernelZechs/open-joystick-display#29]
Not a huge issue, but noticed that https://www.amazon.com/Mayflash-Dreamcast-Controller-Converter-Adapter/dp/B00K7YK0YA gets recognized by the software, but it doesn't register any of the inputs.

**Comment by KernelZechs** [comment]
@zeroviim question for you, did you try changing the player to see if you got another input?

![image](https://user-images.githubusercontent.com/46404303/71445466-0a949800-26e8-11ea-9854-7927cee05a0d.png)

I have a gamecube mayflash adapter and sometimes it registers as player two.

**Comment by zeroviim** [comment]
Ah, that was it, I should've experimented before opening the ticket! Sorry about that, figured since it showed up first in the list on devices and printers it would reg as player 1

Closing the issue

**Comment by KernelZechs** [comment]
@zeroviim Just so you know why, the mayflash registers each controller regardless if it is plugged in or not, you can see this on your Device Manager, so it all depends on which port you plug in. Regardless, I'm happy I was able to help you out, Merry Christmas!
