### ISSUE TITLE
Add support for Logitech G27 racing wheel

### ISSUE THREAD

**Issue by alexbrrsclnt** [KernelZechs/open-joystick-display#32]
Hi!

Is there any option to add support for this wheel?

Thanks in advance!

**Comment by KernelZechs** [comment]
@alexbrrsclnt just so that I understand, are you asking for a G27 theme? Because the G27 should work fine in OJD now that we added racing wheel support.

**Comment by alexbrrsclnt** [comment]
Maybe I am confused because in the configuration mode I see all the buttons of the wheel detected in the input tester, but some are displayed in the preview using the G29 theme, and others don't, like the pedals or the spin of the wheel, and the gears padels are shown inverted.

I have to read the documentation and see how to assing correctly all the buttons.

**Comment by KernelZechs** [comment]
@alexbrrsclnt 

Please read this ticket on how to configure your wheel, TL;DR- you'll just have to make your own custom mapping for the G27: https://github.com/KernelZechs/open-joystick-display/issues/26

**Comment by alexbrrsclnt** [comment]
I finally got the wheel with the correct configuration making a custom mapping profile. You can close this issue. If you get time to add the G27 theme, great, but it's not necessary.

Great work and excelent program!

Congrats!

**Comment by KernelZechs** [comment]
I'm going to close out this ticket, but if I add a G27 theme in the next release I will tag it here. Thanks!
