### ISSUE TITLE
linux installation

### ISSUE THREAD

**Issue by Xathen** [KernelZechs/open-joystick-display#35]
i am wondering how to install the app on a linux os because on your website, i cant find anything about installing on a linux device. if you can help, please tell me. thanks

**Comment by KernelZechs** [comment]
Afternoon @Xathen 

It's very simple:

- Go to https://ojdproject.com/
- Download the latest Linux binary - https://ojdproject.com/downloads/linux/stable/x64/open-joystick-display-2.7.1-x64-linux.tar.gz
- Extract and put it somewhere for you to use (I use the `/opt` folder)
- Run the executable `open-joystick-display` (You can do this via a terminal)

It's pretty simple. If you're using XFCE/KDE/Gnome you can add a quick launcher for it so you can launch it from your GUI. There really isn't an install process- this is to keep it portable to various Linux desktop environments and distros.

Here is a quick video showing the process and how to add it to your XFCE launcher menu. For other window mangers look at guides online.

https://www.youtube.com/watch?v=vaiV2S2K6-s&feature=youtu.be

Let me know if this helps you.

**Comment by KernelZechs** [comment]
I'm closing out this ticket, if you need help just feel free to reopen it.
