### ISSUE TITLE
BUG - Broadcast mode no longer bringing up a window.

### ISSUE THREAD

**Issue by Mastichrono** [KernelZechs/open-joystick-display#50]
Windows 10, latest update for OJD.

I've never had any problems using this in the past, but recently when I click ESC to go into broadcast mode, no window shows up and there is nothing in the OBS list of windows.

**Comment by Mastichrono** [comment]
I forgot to mention that I have uninstalled and re-installed using the most recent release as well.

**Comment by KernelZechs** [comment]
@Mastichrono I just tested it in Windows 10 and it works, likely you changed your monitor configuration and it is off screen and you can't see it.  I would reset your configuration by doing the following:

- Open Open Joystick Display
- Do Reset Config
- Try ESC to enter broadcast mode again.

If you're unable to do the above, you can also do the following:

- Close all instances of Open Joystick Display
- Open Windows Explorer
- In your address bar type: %appdata%
- Move the open-joystick-display folder somewhere else as a backup. (You're resetting the config this way by deleting the old one)
- Open 'Open Joystick Display' again.

Again, I tested this on the latest version 2.8.0, on a fully updated windows 10 and with OBS, it works as expected.
