### ISSUE TITLE
How to make OJD portable?

### ISSUE THREAD

**Issue by FoxyMonty** [KernelZechs/open-joystick-display#51]
On Microsoft Windows 10.

I downloaded the latest portable version and extracted to a folder.
On launch the application is creating folders inside of appdata/roaming.
Is there something I need to do to make the application portable and create all folders within the OJD directory?

On another note, it seems the application says update available when there does not seem to be one.

Was not sure where to post this, sorry if this is the wrong place.

**Comment by KernelZechs** [comment]
@FoxyMonty 

How to build can be found here: https://github.com/KernelZechs/open-joystick-display/blob/master/BUILD.md

By `portable` build it means it doesn't need an installer. Electron by defaults installs configs to the roaming user profile and I'm not going to override this standard configuration.

I will look into why the version is saying there is an update, likely just pulling the wrong tag version from the web.
