### ISSUE TITLE
[Feature Request] Wiimote mapping

### ISSUE THREAD

**Issue by Paragoumba** [KernelZechs/open-joystick-display#53]
Is a Wiimote mapping planned? I think it would be useful, even if OJD will probably not show motions a native mapping of the button inputs might be nice.

**Comment by KernelZechs** [comment]
You can build your own mapping using the mapping tools provided to you. Simply just add a new mapping and assign whatever you need. However, if you're looking for a wiimote theme it's not on the radar but you're free to build your own.

Guides:
Mapper Tutorial: https://ojdproject.com/user-guide#input-mapper
Theme Tutorial: https://ojdproject.com/developer-guide#theme-development
