### ISSUE TITLE
Pro Controller connected via USB doesn't work.

### ISSUE THREAD

**Issue by JettJamez** [KernelZechs/open-joystick-display#56]
I tried connecting my Switch Pro Controller via USB and it just freaks out. The buttons and axis appear to be going on and off at random, with very little correlation with my actual inputs. I tried different profiles, different themes, I'm not much of a coder so I have NO clue what is going on. Please help!

**Comment by KernelZechs** [comment]
You haven't provided enough information to help me with your problem. Please review the ticket template and provide me the information required for a support ticket and resubmit. 

https://github.com/KernelZechs/open-joystick-display/issues/new?assignees=KernelZechs&labels=&template=standard-bug-feature-theme.md&title=

Furthermore, my Switch Pro Controller works just fine with OJD so this sounds like a system configuration error. So maybe look into what is wrong with your system before creating a new ticket.
