### ISSUE TITLE
Enhancement: Option to start in broadcast mode

### ISSUE THREAD

**Issue by EternalBlueFlame** [KernelZechs/open-joystick-display#57]
**- Concept:** 
Provide a start parameter for the program to boot directly into broadcast mode.

**- Example:**
`"/opt/Open Joystick Display/open-joystick-display" %U -broadcast`

**- Primary use:**
I think it would be safe to assume a lot of users use the same controller regularly with infrequent changes, while it's only a minor convenience to skip only having to press escape on start, it would make the program feel more streamlined for users that use it regularly.

If this is already implemented, my apologies, I was unable to find it in the documentation or in web searches.

**Comment by KernelZechs** [comment]
@EternalBlueFlame this already exists, use `--start-broadcast-mode`, this was added in version 2.6.
